### ISSUE TITLE
Could the new SwissQRBill.PDF return a callback or promise?

### ISSUE THREAD

**Issue by Ale-RJP** [Rogerrrrrrrs/SwissQRBill#73]
I having trouble using the library, I want to execute some actions after the swissqr bill is created, I tried some workarounds with no success.

**Comment by Rogerrrrrrrs** [comment]
If I understand it correctly, you are probably trying to read or interact with the generated file right after calling 'new SwissQRBill.PDF()`. This will not work because the file is created with an asynchronous writable stream and the file is not yet fully written. The easiest way is probably to emit an event as soon as the file is completely written. Could this solve your problem?

**Comment by Rogerrrrrrrs** [comment]
v1.2.0 added a callback function as well as a finished event that get executed once the pdf file has been completly written.
You can now execute your actions inside a callback function like this 
```js
const pdf = new SwissQRBill.PDF(data, "qrbill.pdf", () => {
  // Your additional actions
});
```
or you can listen on a finished event like this
```js
const pdf = new SwissQRBill.PDF(data, "qrbill.pdf");

pdf.on("finish", () => {
  // Your additional actions
});
```
